import type { Metadata } from "next";

import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import {
  createTheme,
  ColorSchemeScript,
  MantineProvider,
  AppShell,
  AppShellHeader,
  AppShellFooter,
  AppShellMain,
} from "@mantine/core";
import { Header, Footer } from "@components/common";

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
        <meta
          name="viewport"
          content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
        />
      </head>
      <body>
        <MantineProvider theme={theme}>
          <AppShell header={{ height: 60 }}>
            <AppShellHeader>
              <Header />
            </AppShellHeader>
            <AppShellMain>{children}</AppShellMain>
            <AppShellFooter>
              <Footer />
            </AppShellFooter>
          </AppShell>
        </MantineProvider>
      </body>
    </html>
  );
}
