import type { Metadata } from "next";

import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/carousel/styles.css";
import { createTheme, ColorSchemeScript, MantineProvider } from "@mantine/core";
import { ApolloProvider } from "@apollo/client";
import apolloClient from "./apolloClient";

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{ children: React.ReactNode }>
) {
  const { children } = props;
  return (
    <html lang="en">
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ApolloProvider client={apolloClient}>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </ApolloProvider>
      </body>
    </html>
  );
}
