import type { Metadata } from "next";
import type { LocalePageParams } from "./shared";

import ApolloWrapper from "./ApolloWrapper";
import "@mantine/core/styles.css";
import "@mantine/dates/styles.css";
import "@mantine/carousel/styles.css";
import { createTheme, ColorSchemeScript, MantineProvider } from "@mantine/core";

const theme = createTheme({});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(
  props: Readonly<{ children: React.ReactNode; params: LocalePageParams }>
) {
  const { children, params } = props;
  const { locale } = params;
  return (
    <html lang={locale}>
      <head>
        <ColorSchemeScript />
      </head>
      <body>
        <ApolloWrapper>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </ApolloWrapper>
      </body>
    </html>
  );
}
